### PR TITLE
Add some tests for RCC! These run on the host.

### PR DESCRIPTION
**Pull request by richardeoin**
I'm not entirely sure cargo + travis can do this, but this is a first
attempt. The numerical behaviour of the host platform might not quite
correspond to the target.

### CODE REVIEW

**Comment by hargoniX** [comment]
With over 1k lines the RCC file is already pretty fat imo. Should we really make use of the rust feature to have tests in the same file as the productive code in this case?

**Comment by richardeoin** [comment]
Yes, rcc.rs could do with being broken up. However writing inline was an easy way to test macros in this case, as it avoids using `#[macro_use]` to get access to the macros elsewhere.

Perhaps we could break up rcc.rs by functionality, as has been done [here](https://github.com/stm32-rs/stm32g4xx-hal/tree/master/src/rcc). Particularly the PLL functionality could go to a separate file.

**Comment by richardeoin** [comment]
Do the test pass on travis now?

bors try

**Comment by richardeoin** [comment]
I've broken up rcc.rs into multiple files, with the largest less than 1k lines

**Comment by hargoniX** [comment]
LGTM! it would be suuuuuper cool if we got tests bases on utest running on real world hardware at some point. (Just in case you wanna look further into testing)

**Comment by richardeoin** [comment]
Agreed, unit test running on real hardware would be ideal. Is there any hardware platform that has good peripheral coverage?

**Comment by richardeoin** [comment]
That doesn't impact this PR, so merging now

bors r+

**Pull request merged**
