### PR TITLE
Update for new pac

### PR DESCRIPTION
**Pull request by usbalbin**
This updates this hal to use the stm32h7-staging pac. I am doing this in an attempt to [get the HRTIM peripheral to work](https://github.com/usbalbin/stm32-hrtim/pull/1).

Also, some other hals seems to be moving towards staging pacs aswell. Not sure whats best...

### CODE REVIEW

**Comment by usbalbin** [comment]
@richardeoin here is an attempt at updating the pac. This is needed for using the HRTIM perpheral since there are a lot of errors in the SVD's that have recently been patched. I also believe there has been other improvements such as allowing things like this:

```diff
- (*Gpio::<P>::ptr()).pupdr.modify(|r, w| {
-     w.bits((r.bits() & !(0b11 << offset)) | (value << offset))
- });
+ (*Gpio::<P>::ptr())
+     .pupdr()
+     .modify(|_, w| w.pupdr(offset).bits(value));
```

and likely many other things which I have not yet updated the code for.

Do you want this change? I also understand if you dont wish to move away from the official releases.

**Comment by richardeoin** [comment]
Awesome work. It's great to keep up with the updates to the PAC. Looks like stm32h7-staging is release channel made by @burrbull , I guess to encourage downstream testing before an 'official' `stm32h7` PAC release?

I'd be happy to use the `-staging` PAC on a branch in this repo. That would allow more PRs to be built on top of it.

**Comment by richardeoin** [comment]
I created the `pac16-staging` branch on the repo. You can now make PRs against that branch instead of master.

**Comment by usbalbin** [comment]
Great thanks!

**Pull request closed without merging**
