### PR TITLE
 rcc: write accessors for AHB and APB busses in a macro

### LINKED ISSUE #21: rcc: write accessors for AHB and APB busses in a macro

### PR DESCRIPTION
**Pull request by hargoniX**
Closes #21

### CODE REVIEW

**Comment by richardeoin** [comment]
LGTM :thumbsup:

It is actually possible to have different documentation for each iteration of a macro. With a macro variable like `$doc:expr` (which is a string):
```
#[doc=$doc]
pub struct $AXBn {
```

**Comment by hargoniX** [comment]
I'm actually not sure what's going on with the CI right now, or rather why this worked before if its an error now.

**Comment by jordens** [comment]
#25 needs to land first (or you'd have to target an old `stm32-rs`/`stm32h7`).

**Comment by richardeoin** [comment]
Okay, #25 has gone in.

bors try

**Comment by jordens** [comment]
Bors try again

**Pull request merged**
