### PR TITLE
FDCAN support using the fdcan crate

### PR DESCRIPTION
**Pull request by richardeoin**

### CODE REVIEW

**Comment by yorickdewid** [comment]
Why has this not been merged yet? The crate works and the tests pass

**Comment by richardeoin** [comment]
It's waiting for the stm32-rs/fdcan crate to be released on crates.io. I tagged it on the next milestone so it won't be forgotten!

**Comment by yorickdewid** [comment]
Ah. Thanks. Just let me know if I can help out

**Comment by richardeoin** [comment]
Rebased onto master and use stm32-rs/fdcan from crates.io

**Pull request merged**
