### PR TITLE
Added reset reason impl

### PR DESCRIPTION
**Pull request by diondokter**

### CODE REVIEW

**Comment by diondokter** [comment]
Oh, apparently `#[rustfmt::skip]` is not allowed anymore?
Well, if rustfmt can do what it likes, the code gets really messy for that match.
Any ideas?

**Comment by richardeoin** [comment]
Seems that you can't put `#[rustfmt::skip]` on that `match` block because it's an expression (that evaluates a value). Feel free to put `#[rustfmt::skip]` on the whole function instead :)

**Comment by richardeoin** [comment]
Thanks for the PR @diondokter ! I added support for RM0455 parts which have a slightly different table of reset sources, and tested in on a NUCLEO-H7A3ZI-Q board

**Comment by diondokter** [comment]
Oh hey, great! Yeah, I didn't have time to fix it for other chips, especially since I don't have access to an HUN right now.

Thanks for your time 😁

**Comment by richardeoin** [comment]
No problem!

bors r+

**Comment by richardeoin** [comment]
bors cancel

**Comment by richardeoin** [comment]
I just fixed some minor spelling items 😀 

bors r+

**Pull request merged**
