### PR TITLE
Add support for MCO pins, also small improvements to rcc

### PR DESCRIPTION
**Pull request by richardeoin**
MCO = Micro-Controller Out pins, PA8 and PC9

### CODE REVIEW

**Comment by hargoniX** [comment]
While we're at fixing the cortex-m-rtfm fail from the CI, it might be useful to just switch to the new name cortex-m-rtic as well? (it got renamed)

**Comment by richardeoin** [comment]
I'll make a new PR for the

**Comment by richardeoin** [comment]
RTFM actually broke two things here: 

* The rename breaks the examples, because we have `#![deny(warnings)]` 
* The latest rtfm/rtic breaks our MSRV (1.40.0)

I've switched the CI to github actions so it's not painfully slow. It only tests against the latest stable rust now.

**Pull request merged**
