### PR TITLE
Implement tick_timer() for LPTIM'ers

### PR DESCRIPTION
**Pull request by noppej**
Proposed implementation for issue #148

### CODE REVIEW

**Comment by noppej** [comment]
@richardeoin ... As discussed, can you please review and comment?  Tx :)

**Comment by richardeoin** [comment]
Thanks for fixing the counter register read! That was a real bug for TIM1/8/12/13/14 (but I think not the other timers, or the LPTIMs), as the UIF bit was being read alongside the counter value. In any case explicitly specifying the field is better.

For your implementation of LPTIM `tick_timer`, I don't think it does what I expect `tick_timer` to do. `LpTimer::$timx` calls `start` and that calls `priv_set_freq`, which configures the timer to *overflow* at the given frequency, not count up at that frequency. 

I think it needs to be more like
```rust
let ticks = clk / frequency;
assert!(ticks < 128);

// Calculate prescaler
let (prescale, prescale_div) = match ticks {
.
.
```
(note there's no divide by `1 << 16`)

But otherwise accessing the ARR register to "fix" it is OK! I think this code does work for the special case where the frequency > `lptim_ker_ck` (clk), because in that case `ticks == 0` therefore `ticks == ticks / (1 << 16)`.

Perhaps you just need to multiply the frequency by `(1 << 16)`?

**Comment by noppej** [comment]
@richardeoin You make some good points above. In my original implementation, I felt a bit 'burdened' by the fact that `LpTimer::$timx` does things that needs to be 'undone' for `tick_timer` but I will try to clean it up as much as possible. In the meantime, I have another related question from looking at the `tick_timer` implementation for the regular TIMs. 

The code currently ( [timer.rs#L272-L273](https://github.com/stm32-rs/stm32h7xx-hal/blob/9426c3fa6d10e847bd739843322f07ef31d21071/src/timer.rs#L272-L273) ) enables a UEV Event on timer overflow.  The documentation doesn't say anything about enabling events. My question to you ... should I enable that event for LPTIM implementation also, or ???

**Comment by ryan-summers** [comment]
In my humble opinion, I think the timer implementation needs to be re-thought-out. Right now, it's hard to use timers provided by the HAL for precision control applications because it allows either an unknown tick value or an unknown tick frequency. I think it would also be desirable to add a timer API to specify tick rate + count so that it's easy to specify the timer configuration precisely when users need to, but that's likely something that I should break into a separate issue/PR.

**Comment by noppej** [comment]
@ryan-summers ... I agree. I've resorted to register level code to achieve my use cases. It does seem to be an API that is shared across multiple stm32 hal's and your suggestion will likely result in breaking changes. I am new to this community, so not sure where to start the conversation. Any suggestions?

**Comment by richardeoin** [comment]
Reopened after it was closed by an errant bors

**Pull request merged**
