### PR TITLE
qei: remove two unsafes, one unnecessary

### PR DESCRIPTION
**Pull request by richardeoin**

### CODE REVIEW

**Comment by jordens** [comment]
LGTM but I don't know about the how/who/when of merging.
We can let bors give it a try:

bors try

**Comment by richardeoin** [comment]
Should be good to roll now https://github.com/stm32-rs/stm32-rs/pull/241 is in

**Comment by richardeoin** [comment]
bors ping

**Comment by richardeoin** [comment]
Just merging manually for now

**Comment by jordens** [comment]
I think @adamgreig needs to add it. I wasn't allowed to.

**Comment by adamgreig** [comment]
It's done

**Pull request merged**
