### PR TITLE
Add support for STM32H725/735 parts

### PR DESCRIPTION
**Pull request by richardeoin**
Reference Manual is RM0468

Ref #163 

- [x] Updates to support STM32H725/735 parts
- [x] Successfully build examples
- [x] At least one example for these parts specifically - _examples/ethernet-rtic-stm32h735g-dk.rs_
- [x] Fix other breakages from https://github.com/stm32-rs/stm32-rs/pull/554
- [x] Remove dependency on nightly PAC build

### CODE REVIEW

**Comment by richardeoin** [comment]
Rebased onto master

**Comment by korken89** [comment]
Hi, this should now be possible with the `0.14` release of `stm32h7`.

**Comment by richardeoin** [comment]
Someone is keen to start using this 😄  . Indeed now that #240 is merged it just needs a rebase

**Comment by korken89** [comment]
Hehe guilty as charged 😅
I've got a nucleo with Ethernet coming in a few days so I'm very much looking forward to trying out this HAL

**Comment by richardeoin** [comment]
@korken89 Have you been able to try this out? Unless there's any major problems, I plan to merge this PR into master and make new issues for anything else that comes up.

**Comment by korken89** [comment]
I have been successfully using it for 1 week now :)

**Comment by richardeoin** [comment]
Great! Let's merge it

**Pull request merged**
