### PR TITLE
Add new blinky example using GPIOs on STM32H747i-Disco

### PR DESCRIPTION
**Pull request by youndong**
Add new blinky example using GPIOs on STM32H747i-Disco

- GPIO port : PI12 for LED1
- GPIO port : PI13 for LED2
- GPIO port : PI14 for LED3
- GPIO port : PI15 for LED4

by Youndong (youndong.park@gmail.com)

### CODE REVIEW

**Comment by richardeoin** [comment]
Thanks for the update! Usually you can continue to use the same PR when you make updates, but this is also fine :)

**Comment by richardeoin** [comment]
The check 'Nightly rust examples' is expected to fail at the moment. The 'Code formatting check' is failing because of trailing whitespace in your file. If you're able to tidy that up, it would the pass and I can directly merge this

**Comment by youndong** [comment]
@richardeoin, I just updated the file with trailing whitespaces removed.

**Comment by richardeoin** [comment]
Thanks. This PR is completed, I will merge it soon.

**Review by richardeoin — APPROVED** [review]

**Pull request merged**
