### PR TITLE
Add link to BSP's for NUCLEO-H743ZI and Daisy Seed

### PR DESCRIPTION
**Pull request by antoinevg**
This pull request updates the README.md file to add links to board support packages for the NUCLEO-H745ZI and Daisy Seed boards.

### CODE REVIEW

**Comment by mtthw-meyer** [comment]
Oh, someone else is working on daisy stuff?! I've been working on a BSP over here https://github.com/mtthw-meyer/libdaisy-rust

**Comment by antoinevg** [comment]
I've gone with a pretty bare-bones approach but thought it might be useful for others if I linked to it.

I like your approach as well, it tracks more closely to the original C++ libdaisy which would make it a lot more accessible for folk wanting to transition across to Rust.

…and it looks like you've gotten the external sdram working, you should link yours too!

**Comment by mtthw-meyer** [comment]
Once I get a few more things ironed out and do a 0.1.0 release. I fixed the DMA example in the HAL but I can't get it working in my crate yet for some reason.

**Review by richardeoin — APPROVED** [review]

**Comment by richardeoin** [comment]
^ I'll retry when github actions is fixed

**Pull request merged**
