### PR TITLE
Minimal requirements for targeting the Cortex-M4 core

### PR DESCRIPTION
**Pull request by richardeoin**
Replace memory.x with core1.x, then build for stm32h747cm4 target

### CODE REVIEW

**Comment by richardeoin** [comment]
With this PR, you should be able to build a minimal example for the Cortex-M4 core by running
```
cp core1.x memory.x
cargo build --features rt,stm32h747cm4 --examples
```

**Comment by noppej** [comment]
Hi @richardeoin ... Is there any chance you can promote this to an up-to-date branch that I can use for testing?

**Comment by richardeoin** [comment]
No, I don't plan to update this PR at the moment. Feel free to make your own branch, take the ideas/snippets and experiment yourself. 

If a better/newer PR gets merged on this topic, then this one would be closed.

**Comment by richardeoin** [comment]
Reopened after it was closed by an errant bors

**Comment by richardeoin** [comment]
Closing in favour of #254

**Pull request closed without merging**
