### PR TITLE
Fix eth::DesRing alignment

### PR DESCRIPTION
**Pull request by tlevora**
Fixing issue https://github.com/stm32-rs/stm32h7xx-hal/issues/507.

### CODE REVIEW

**Comment by richardeoin** [comment]
I suspect the `packed` annotation was originally an attempt to prevent padding between the members of the struct. However it forces only byte alignment of the struct itself, which is not intended. And the `repr(C)` is sufficient to prevent padding.
* Would it make sense to remove all the uses of the `packed` annotation?
* Why not add the `align(4)` annotation?
* There's a comment on line 190 that refers to "packed", maybe good to remove this too

**Comment by tlevora-dtml** [comment]
> I suspect the `packed` annotation was originally an attempt to prevent padding between the members of the struct. However it forces only byte alignment of the struct itself, which is not intended. And the `repr(C)` is sufficient to prevent padding.
> 
> * Would it make sense to remove all the uses of the `packed` annotation?
> * Why not add the `align(4)` annotation?
> * There's a comment on line 190 that refers to "packed", maybe good to remove this too

Originally I wanted to make just a minimal code update to fix the issue, eventually I decided to review all the related `repr` statements and here is my opinion:
- `[TR]Des` structs
  - They must be `repr(C)` because of ordering.
  - Alignment of all their members is platform specific, which means it should be 4 for `u32` on our target platform.
  - If we prefer the code to be **portable**, we can explicitly define the alignment to be **`align(4)`**.
- `[TR]DesRing` structs could be `repr(Rust)` because
  - `[tr]d` has already defined proper order and alignment
  - `[tr]buf` shall be aligned to 4 (platform specific) and there should be no padding between values in the array, because `u32` size is 4.
  - `[tr]didx` shall be aligned to 4 (platform specific), so that no hard-fault can occur because of unaligned access.
  - The member order is not important at all.
  - Padding between members does not matter at all. _(But there is no padding.)_

What do you think?

**Comment by tlevora** [comment]
> I suspect the `packed` annotation was originally an attempt to prevent padding between the members of the struct. However it forces only byte alignment of the struct itself, which is not intended. And the `repr(C)` is sufficient to prevent padding.
> 
> * Would it make sense to remove all the uses of the `packed` annotation?
> * Why not add the `align(4)` annotation?
> * There's a comment on line 190 that refers to "packed", maybe good to remove this too

Originally I wanted to make just a minimal code update to fix the issue, eventually I decided to review all the related `repr` statements and here is my opinion:
- `[TR]Des` structs
  - They must be `repr(C)` because of ordering.
  - Alignment of all their members is platform specific, which means it should be 4 for `u32` on our target platform.
  - If we prefer the code to be **portable**, we can explicitly define the alignment to be **`align(4)`**.
- `[TR]DesRing` structs could be `repr(Rust)` because
  - `[tr]d` has already defined proper order and alignment
  - `[tr]buf` shall be aligned to 4 (platform specific) and there should be no padding between values in the array, because `u32` size is 4.
  - `[tr]didx` shall be aligned to 4 (platform specific), so that no hard-fault can occur because of unaligned access.
  - The member order is not important at all.
  - Padding between members does not matter at all. _(But there is no padding.)_

What do you think?

**Comment by richardeoin** [comment]
Thanks for the clear explanation! I'm agreed.

> [TR]Des structs

The code doesn't need to be portable since this crate specifically targets a 32-bit architecture. So agreed with `repr(C)` and that the comment explains it sufficiently

**Pull request merged**
