### PR TITLE
WIP: Refuse PRs with clippy warnings

### PR DESCRIPTION
**Pull request by phoracek**
Prevent code violating clippy warnings from getting into the repository. The codebase now contains many unused imports and other more or less serious code smells. These issues can be prevented with a harsher CI.

Follow-up patches will address all the current warnings.

WIP: This still needs to address all those issues.

Signed-off-by: Petr Horacek <hrck@protonmail.com>

### CODE REVIEW

**Comment by phoracek** [comment]
@richardeoin is this something desirable for the repo? And if so, would you please allow workflows to run, so it starts yelling at me? Thanks!

**Comment by richardeoin** [comment]
And in general yes, I'm in agreement that the CI should error on Clippy lints that are `warn`, `deny` or `forbid`. `allow` level lints should be allowed still imo. https://doc.rust-lang.org/rustc/lints/levels.html

The PR is a possible dupe of https://github.com/stm32-rs/stm32h7xx-hal/pull/234

**Comment by richardeoin** [comment]
In general yes, I'm in agreement that the CI should error on Clippy lints that are `warn`, `deny` or `forbid`. https://doc.rust-lang.org/rustc/lints/levels.html

This PR is a possible dupe of https://github.com/stm32-rs/stm32h7xx-hal/pull/234

**Comment by phoracek** [comment]
I see. +1 on voluntarily ignoring some lints with `allow`. Closing this PR in favor of #234 for now.

**Pull request closed without merging**
