### PR TITLE
USB: Implement instructions_per_us

### PR DESCRIPTION
**Pull request by mattico**
A minor improvement on #187 if https://github.com/stm32-rs/synopsys-usb-otg/pull/16 is merged/released.

### CODE REVIEW

**Comment by richardeoin** [comment]
Nice, this looks great. I'll wait and see what happens upstream before picking this or #187

**Comment by mattico** [comment]
We could merge #187 for 0.8.0, maybe including changing the clock argument to be `&CoreClocks` so we're ready for this when upstream is.

**Comment by richardeoin** [comment]
Let's do that over on #187

**Comment by mattico** [comment]
`force_reset` is being implemented in a way that doesn't require this change anymore.

**Pull request closed without merging**
