### PR TITLE
USB example improvements

### PR DESCRIPTION
**Pull request by richardeoin**
- [x] Add notes about internal USB regulator to examples
- [x] Add an interrupt-driven example for USB, maybe using RTIC

### CODE REVIEW

**Comment by mattico** [comment]
I was going to enable `xcvrdly` with synopsys-usb-otg 0.3.0, background information: 

It should be safe to enable this on all ULPI PHYs: https://github.com/hathach/tinyusb/pull/1195/files. I believe it should be safe to enable when using the internal PHY as well, but I haven't been able to get USB working on my nucleo board to test it.

If we can't just enable xcvrdly when using the internal PHY we should expose it as a feature.

**Comment by richardeoin** [comment]
Sounds good, we should enable this if we can. I have a H747I-DISCO board (with a USB3320C PHY) to test on.

Interesting that you can't get the on board FS PHY working on your nucleo, do you have any idea why?

**Comment by mattico** [comment]
ESD or IO pin current injection maybe. Pretty sure it used to work and that it's not software related.

**Comment by richardeoin** [comment]
@mattico Could we just add [this text](https://github.com/stm32-rs/synopsys-usb-otg#ulpi-transciever-delay) to the [module-level docs](https://docs.rs/stm32h7xx-hal/latest/stm32h7xx_hal/usb_hs/index.html) with an explaination of how to enable `synopsys-usb-otg/xcvrdly` ? Since cargo dependencies are a union through the tree, and this crate doesn't specifically need `xcvrdly`, it seem more cargo-y to let users select it for themselves.

**Comment by richardeoin** [comment]
Rebased onto master and added ULPI Transciever Delay to documentation

**Pull request merged**
