### PR TITLE
DAC implementation

### PR DESCRIPTION
**Pull request by richardeoin**
Implementation of a trait that is not in embedded-hal but is common to several of the
other stm32-rs crates

### CODE REVIEW

**Comment by richardeoin** [comment]
This still needs more testing or review

**Comment by astraw** [comment]
This works for me on h743 rev v (nucleo board). I tested both channels. Thanks.

One feature that might be useful but not covered here is simultaneous updating to both DACs. Another is running the DAC without the output buffer. Perhaps these are out-of-domain for the HAL.

**Comment by richardeoin** [comment]
Thanks for testing, that is very useful!

The `set_value` call should optimise down to a single register write for each channel, so at the instruction level sequential calls to `set_value` should be very similar to a single function call. But if there was a neat way to write simultaneous updates it could go in.

Selecting the output buffer would be a good addition though.

**Comment by richardeoin** [comment]
I changed the API to add typestates here, as used in the ADC implementation. This removes the simple usage error of calling `calibrate` after `enable`. I also added an `enable_unbuffered` method to support usage without the output buffer.

**Comment by astraw** [comment]
Sounds good.

As far as I read the manual, calibration is only relevant for the buffered operation. Perhaps extending the typestates further, calibration could only be possible in buffered mode?

But I am afraid we move beyond the A (abstraction) in HAL here - how many other devices are going to have similar behavior? On the other hand, this is also a crate for ease-of-use of the h7xx series.

**Comment by richardeoin** [comment]
That's true, but also calibration doesn't break unbuffered mode. So I see no reason to restrict it. 

Perhaps re-naming `calibrate` to `calibrate_buffer` makes the hardware effect obvious?

**Comment by astraw** [comment]
I like it.

**Pull request merged**
