### PR TITLE
Update sdmmc support

### PR DESCRIPTION
**Pull request by richardeoin**
Update sdio-host version and improve eMMC support

### CODE REVIEW

**Comment by richardeoin** [comment]
@ostenning There's a few changes to the sdmmc support here, it would be helpful if you could try this out!

**Comment by ostenning** [comment]
Hi @richardeoin , I've given this branch a fairly quick test with the `embedded-sdmmc` crate, reading / writing data to the FAT32 formatted SDCard. I've had no problems as of yet.

**Comment by richardeoin** [comment]
Thanks @ostenning 👍  I was looking for a sanity check really, so that test with `embedded-sdmmc-rs` is great

**Comment by burrbull** [comment]
@richardeoin Do you plan to update f4xx-hal also?

**Comment by richardeoin** [comment]
@burrbull No I don't plan to update f4xx-hal. The F4 reference manuals I found don't mention eMMC at all (although it might still be possible..) and I don't have any f4 + eMMC hardware to test on

**Pull request merged**
