### PR TITLE
Update stm32h7

### PR DESCRIPTION
**Pull request by mattico**
stm32h7 should have a release soon. Preparing for that.

### CODE REVIEW

**Comment by mattico** [comment]
Hmm, some DAC changes as well.

**Comment by mattico** [comment]
see https://github.com/stm32-rs/stm32-rs/pull/499

**Comment by richardeoin** [comment]
Thanks for this! I'll finish off the DAC changes, in this case adding new type parameters in the right place can get a bit tricky..

**Comment by richardeoin** [comment]
Hmm, when building the RTIC examples we end up with both cortex-m 0.6 (from RTIC) and cortex-m 0.7 (everything else) in the tree, and the compiler sees types from each version as distinct.

Potentially this can be resolved by tweaking the examples

**Comment by mattico** [comment]
The newer releases of cortex-m 0.6 re-export the types from cortex-m 0.7, so you should be able to just call `cargo update`.

**Comment by mattico** [comment]
I see now that stm32 0.6 is not fully forward compatible: https://github.com/rust-embedded/cortex-m/issues/333

**Comment by richardeoin** [comment]
Looks good, I added a little more explanation in the changelog.

bors r+

**Pull request merged**
