### PR TITLE
update GPIO 2

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
cc @richardeoin

**Comment by mattico** [comment]
I am 👍 on this because I end up switching pins from pull-up to pull-down in certain situations and having the typestate makes this very annoying.

**Comment by mlamoore** [comment]
It looks like you removed pull-up and floating from some examples but never
set the input type elsewhere. I feel like the examples should set the input
type to maintain previous functionality, especially for simple dev board
setups that often rely on the internal pull ups to set signal level of
buttons etc...

**Comment by burrbull** [comment]
> It looks like you removed pull-up and floating from some examples but never set the input type elsewhere.

`into_pull_up_input` never gone. It is just not present in type definition now.

**Comment by mlamoore** [comment]
Oops, sorry about that. I was just looking at the diff which said nothing
about pull-up/pull-down, the initialization didn't change so I didn't
examine closely enough.

Looks great to me!

**Comment by burrbull** [comment]
rebased on #347

**Comment by burrbull** [comment]
rebased

**Comment by richardeoin** [comment]
@burrbull Is this ready to merge?

**Comment by burrbull** [comment]
should be

**Comment by richardeoin** [comment]
Ok thanks, let's merge it

**Pull request merged**
